### ISSUE TITLE
Is it possible to add description to each of the states in yaml file?

### ISSUE THREAD

**Issue by swaticolab** [AlexandreDecan/sismic#102]
HI,

I am trying to add description to each of the states in the sismic yaml file. Is there any way to do it?

**Comment by AlexandreDecan** [comment]
Hello,

No, there is no such key for a state. The key only exists for `statechart`.
However, you can use YAML comments to document a state (or any other line) in the YAML file, but these comments won't be loaded nor considered by Sismic.
