### ISSUE TITLE
GUI for designing state charts and Auto generating of python code

### ISSUE THREAD

**Issue by chansdad** [AlexandreDecan/sismic#106]
Is there any plan for a gui to design state charts ? i saw that there is an old version in one of the branches . Are you planning on rewriting it with newer technologies? Also any plan on autogenerating the python code ?
THanks

**Comment by AlexandreDecan** [comment]
Hello,

There is an ongoing project that aims to develop a prototype of a GUI to design and edit statecharts, but no plan to integrate this as part of Sismic. 

Code generation is out-of-scope. Since Sismic is a library and since it already interprets statechart, generating code wouldn't make a difference in practice.

**Comment by chansdad** [comment]
Any idea when the GUI will be released? is it going to be tk based or a web based GUI?  By code generation , i am referring to the code to invoke the methods for a given state chart from an external program .
Thanks .

**Comment by AlexandreDecan** [comment]
Hello,

For the GUI: probably not before June or July. Anyway, the GUI will be a prototype that (1) will not be implemented in Sismic (it is an external project) and (2) does not replace the intuitive definition of statecharts in YAML. 

For code generation: Could you please elaborate a little bit? I'm not sure I understood exactly what you aim to do.

**Comment by AlexandreDecan** [comment]
I forgot to answer one of your question: the GUI won't be based on `Tk`, but will be a web-based GUI. Even if it's a prototype, we hope to integrate it as part of our documentation on https://sismic.readthedocs.org or to some online platform so users will benefit from it without having to install it locally.

**Comment by chansdad** [comment]
Hi Alexandre , 
Any progress on the GUI ? Finally i got my project restarted after a long delay and seems like i got what i needed so far , with the exception of a GUI that one can use to create sismic compliant statechart . If you already started on the project and need any further assistance let me know and i could probably contribute as well .  Must say Sismic worked well for my use case .

**Comment by AlexandreDecan** [comment]
Hello,

A student of us worked on a prototype of a GUI a few years ago. You'll find his repository there: https://github.com/pierre503/Sismographe   It has several limitations and doesn't support all the features of Sismic, but can still be a good starting point to create "simpler" statecharts :-)

**Comment by AlexandreDecan** [comment]
The tool can be used online here: https://pierre503.github.io/Sismographe/
