### ISSUE TITLE
Integration with statechart

### ISSUE THREAD

**Issue by chansdad** [AlexandreDecan/sismic#107]
There are two examples , "Controlling a statechart from within the environment" and "Controlling the environment from within the statechart".

Can we mix both the strategies? I want to be able to  control the statechart from within the environment as well as controlling the environment from within the statechart. Have you tested this or what are your thoughts on this ?

Thanks

**Comment by AlexandreDecan** [comment]
Hello,

Of course, both strategies can be mixed ;)

**Comment by chansdad** [comment]
That is what i thought , just wanted to make sure before i dive deep.

**Comment by AlexandreDecan** [comment]
Perfect then ;-) 

I close this issue. Feel free to open new ones if you have question, I'll be happy to help you.
