### ISSUE TITLE
Consider adding "statechart modeling and simulation" playlist to documenation

### ISSUE THREAD

**Issue by rajivr** [AlexandreDecan/sismic#112]
Again, I discovered  this by accident. It would be nice if [statechart modeling and simulation](https://www.youtube.com/playlist?list=PLmHMvhX5wK_aohX5sOeAMogFDwlc3gJYR) playlist can be added somewhere in the documentation or `README.md`.

While its not directly related to sismic, many core ideas are nicely and visually explained.

**Comment by AlexandreDecan** [comment]
@tommens I let you integrate this (either in the readme, or preferably in the documentation). If you're aware of other resources, perhaps we can even have a "Resources" subsection

**Comment by tommens** [comment]
I will integrate it, given that it was me that created this playlist, and was the author of all videos in the playlist ;-) I will let you know when it is integrated.
