### ISSUE TITLE
Suggest to loosen the dependency on schema

### ISSUE THREAD

**Issue by Agnes-U** [AlexandreDecan/sismic#118]
Hi, your project sismic(commit id: ec4e998a47fb235d407349e134d7c1c6e137df9c) requires "schema==0.6.2" in its dependency. After analyzing the source code, we found that the following versions of schema can also be suitable, i.e., schema 0.5.0, 0.6.0, 0.6.1, since all functions that you directly (5 APIs: schema.Schema.__init__, schema.Optional.__init__, schema.Use.__init__, schema.Or.__init__, schema.SchemaError.__init__) or indirectly (propagate to 2 schema's internal APIs and 0 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on schema from "schema==0.6.2" to "schema>=0.5.0,<=0.6.2". This will improve the applicability of sismic and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on schema?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by AlexandreDecan** [comment]
https://github.com/AlexandreDecan/sismic/blob/3309dd7f6c21677f8f2b652c37f74880e31ce81a/setup.py#L53
