### ISSUE TITLE
plantuml-1.2022.12 issue with `note top of`

### ISSUE THREAD

**Issue by rajivr** [AlexandreDecan/sismic#119]
I have a sismic [yaml](https://github.com/fdb-rs/fdb/blob/fdb-0.3.1/fdb/sismic/range_result_state_machine.yaml) file that I use to visualize with `sismic-plantuml`.

When I do

```
sismic-plantuml --show-description --show-preamble range_result_state_machine.yaml
```

The generated uml file can no longer be visualized using plantuml as it generates a parsing error. Here is the [gist](https://gist.github.com/rajivr/817f5356536901e10a7277bbb111fe79) of the file.

However, if I move the `note` to the end of the uml file, it parses correctly.

Here is the [gist](https://gist.github.com/rajivr/5fcd0d5bcf625589d9dee47e893e359c) to the working file.

**Comment by AlexandreDecan** [comment]
Hello, 

Thanks for reporting this issue! I'm using a slightly older version of PlantUML and I cannot reproduce the bug. Can you test with the latest version of PlantUML? 

Note that if moving the note to the end of the definition is enough to make it works, that's an easy patch for Sismic ;-)

**Comment by tommens** [comment]
If the issue is due to the fact that we did not take into account notes / comments in the yaml files for the plantuml generation, then I guess the fix could be to ignore (or temporarily remove) all commented lines before actually running the PlantUML generator? Asking users to move all comments in their yaml files to the end does not seem to be a user-friendly solution?

**Comment by AlexandreDecan** [comment]
From what I understood, that's not the situation : when the preamble of a state chart is included in the plantuml output (in the form of a note), it does not work except if the note is moved after state definitions. I'm waiting for a confirmation but I already have a potential fix locally (basically to export all notes after state definitions).

**Comment by rajivr** [comment]
> Thanks for reporting this issue! I'm using a slightly older version of PlantUML and I cannot reproduce the bug. Can you test with the latest version of PlantUML?

@AlexandreDecan @tommens Thanks for the quick reply!

The error can easily be reproduced on the [PlantUML Online Server](http://www.plantuml.com/plantuml/uml/bLDFwzim3BtdKvZVQGlviNiFezsVmHZTe8DTnWXgehIcZbriERI4VlTPJfQMKhThw472qjDxwjFS4LZohSf8aaAn0ht15Jglw2S1uHAghTGeOb9jGssc3Q4WinUcIPLdGkJvHwC93pJBSx4oXY84lxpU_iBBrxRr16k5iv08GHQqWugaqJ5t6lPkQoWchQan1XOxj8xZy5jUzaj22rEtagqSMjUuaRfqg6A6kXxZr_HtBUWB4WlTt1UL4jRKwxBnv2sMEpoM7IYF9LWBnpJIOqxVyFYBaHOCjEX0AfwOPlZ_V2lZDSLerxbn-_RcndMDXn0zI_spjSOEJCMRHcfGRn-Z91QBZ9MXhWKRDNCHz2LXr1S1BkdvFc3-ply47k-dFpmJgJrp5LVFXjfFXizWwdloEIwad-ISGkaevFPqrf4YnZBkifv8ZCE_uu4-G0Zwj56PqGMhVn3COyABawyq9cYCat_i-k2mOl1HCVYkY6OxYNV2xsiW70wvE5ztSJxeOhfcPdVAvY7rhVeB).

The above link will show you the error that I am seeing.

**Comment by AlexandreDecan** [comment]
Thanks for sharing this! This seems to confirm what I thought: more "recent" versions of PlantUML require "notes" related to states to be defined after state definition. I'll test my local fix and release it ASAP. 

Concerning the second "issue" (from the yaml file: "Even though there are two final states - Error and Done, plantuml shows it as one done state.") there's unfortunately nothing I can do about this, since that's a limitation from PlantUML (only one final state can exist in a same state) :-/

**Comment by rajivr** [comment]
> Concerning the second "issue" (from the yaml file: "Even though there are two final states - Error and Done, plantuml shows it as one done state.") there's unfortunately nothing I can do about this, since that's a limitation from PlantUML (only one final state can exist in a same state) :-/

Thanks for quick fix on this issue @AlexandreDecan!

I do have a suggestion for you and @tommens. :-)

It would be really awesome if you can create a course on "Statecharts from the ground up!" where you teach the fundamental data structures and design considerations for implementing a statecharts.

I would love to attend such a course and I also think it would be a very useful skill for programmers to have when they encounter complex design problems.

**Comment by tommens** [comment]
@rajivr if you were looking for a tutorial on how to create statecharts from scratch, I have videos on this, using another visual tool called Yakindu (now rebranded into Itemis Create). This should be a good entry point for people wishing to learn how to use and create statecharts. Is this what you were looking for?
https://www.youtube.com/playlist?list=PLmHMvhX5wK_aohX5sOeAMogFDwlc3gJYR
