### ISSUE TITLE
python code running

### ISSUE THREAD

**Issue by EdoardoBagnati** [AlexandreDecan/sismic#126]
Hi, I wanted to ask because I didn't quite understand: how do I associate the "remove_from_queue" on entry action of the "machine_interpreter" state chart with the following code?
![Screenshot 2024-08-04 175008](https://github.com/user-attachments/assets/d659a72f-40eb-4c9f-8254-11e605794137)
![Screenshot 2024-08-04 175035](https://github.com/user-attachments/assets/b01ebe0e-4ae0-4af5-ae1b-1adb7445528e)
 I used this command, but it doesn't work:
![Screenshot 2024-08-04 180126](https://github.com/user-attachments/assets/bec139ce-2bcf-4a9d-b977-a460cc42f23e)
.Could you give me a suggestion? Thanks in advance.

**Comment by AlexandreDecan** [comment]
I'm still waiting for a simple "thanks" for the other issue I spent time it for you. Read the doc, learn the language and the library first.

**Comment by EdoardoBagnati** [comment]
I'm really sorry, I was being foolish. I'm a beginner in Python, and I'm very absorbed in this project, so I didn't realize I hadn't responded to you. That's also why I sometimes ask basic questions. Anyway, thank you so much; I'm going to focus on it now.
________________________________
Da: Alexandre Decan ***@***.***>
Inviato: Sunday, August 4, 2024 7:21:51 PM
A: AlexandreDecan/sismic ***@***.***>
Cc: Edoardo Bagnati ***@***.***>; Author ***@***.***>
Oggetto: Re: [AlexandreDecan/sismic] python code running (Issue #126)


I'm still waiting for a simple "thanks" for the other issue I spent time it for you. Read the doc, learn the language and the library first.

**Comment by AlexandreDecan** [comment]
The problem is that you do not seem to know how python works, hence you do not know how to use the library. The question you ask is not related to sismic but to python. I'm willing to help for issues related to sismic, I won't help for python.
