### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by tommens** [AlexandreDecan/sismic#14]
In the documentation, I would suggest to move out the part "Defining statecharts in Python" (from the "Defining statecharts" section), and move it to the "Advanced topics" section. It is not really the basic intended use of Sismic, so it fits more as advanced topic.
Before doing so, however, please integrate my previous pull request first, since it also makes changes to the "Defining statecharts" section...

**Comment by AlexandreDecan** [comment]
I removed this part of the documentation. It was just some pointer to the API. I do not expect people to define statecharts in Python.
