### ISSUE TITLE
Possible confusion with *send* function

### ISSUE THREAD

**Issue by tommens** [AlexandreDecan/sismic#18]
In the current version of Sismic, the *send* function is used in two different ways, which may cause confusion to users:
- Within a statechart description, *send* can be used as an action to raise and send a new event. The syntax for this is, for example send('floorSelected', floor=4) if one wants to raise a parameterised event, or simply send('floorSelected') if it is a parameterless event.
- Within a statechart Interpreter however, in order to *send* an event one has to use the following syntax: interpreter.send(Event('click’))

I understand why there is this difference, but it may nevertheless be confusing, especially because both functions are called *send*. To avoid this confusion, one could rename one of both sends. Here are 2 possibilities:
- Use raise(...) instead of send(...) within the statechart descriptions, and keep send(...) within the statechart intepreter
- Keep send() within the statechart descriptions, and use fire(...) or trigger(...) within the statechart interpreter.
- other possibilities?
I am not sure which renaming would be the most appropriate. Preferably one that is the closest to the SCXML syntax (for those SCXML users that would like to use our approach...)

**Comment by AlexandreDecan** [comment]
Using ``raise(...)`` is not allowed in Python as it is a language keyword. SCXML makes use of ``send`` within statechart description, so I suggest we do not change the ``send`` function within statechart. 

What do you think of ``interpreter.queue(...)``? It seems more appropriate than ``trigger`` as it suggests that nothing actually executes when you call this method.

**Comment by tommens** [comment]
Ok, let us keep send in the statechart descriptions, and use queue(Event ...) in the interpreter for the lack of a better term. In any case, it will be clear that an Event is queued, since one needs to explicitly pass an Event object as parameter to the queue method...
(By the way, I am not sure that you can label this issue as a "refactoring" if it will be an API-breaking change. Refactorings are supposed to be behaviour preserving, but they are also supposed to preserve the API... This is just a minor detail, however, since we are not yet at release 1.0).

**Comment by AlexandreDecan** [comment]
You're right about *refactoring*. I added a *breaking change* label. 
I'll do the change this afternoon, I need to adapt the documentation, the tests, the examples, etc.

As Sismic seems to have (at least a little) visibility, I'll add and complete a *CHANGELOG.rst* .
