### ISSUE TITLE
Style checker for statecharts

### ISSUE THREAD

**Issue by tommens** [AlexandreDecan/sismic#21]
Probably an issue request to the tagged under "utopia", or "nice to have", as it is not a priority for the moment, but nevertheless useful for people that would like to develop executable statecharts:

A "style checker" for statecharts would provide warnings if the statechart specification does not follow a nice "modelling style" or does not respect the common "modelling conventions" for statecharts. It would be the equivalent for the many style checkers that already exist for programming languages (e.g. PMD, CheckStyle, and many other static code analyser tools that aim to assess structural code quality).

A style checker goes beyond a statechart validation tool (which simply checks for syntactic correctness of the statechart): it should typically rule based, composed of a number of rules that verify if the modelling style and modelling conventions are respected. The user should be able to easily configure, enable or disable some rules, in order to customise the style checker to his own needs. It should also be easy to add and share new rules.

**Comment by AlexandreDecan** [comment]
Could you please provide some examples of such rules?

**Comment by AlexandreDecan** [comment]
Not enough information.

**Comment by tommens** [comment]
C�est bizarre, pendant les vacances de noel j�avais r�dig� tout une liste d�exemples de style guidelines que je croyais avoir mis sur github, mais je ne le vois nullepart (meme pas dans ma branche a moi). Je ne sais pas o� ils sont all�s je crains qu�ils se sont perdus dans le trou noir de l�internet�

Tom Mens

**Comment by AlexandreDecan** [comment]
:'(
