### ISSUE TITLE
initial state change

### ISSUE THREAD

**Issue by aliparsai** [AlexandreDecan/sismic#31]
It would be nice to have a method that can change the initial state of a statechart/ anything with a compositemixin.
I can change it myself from inside mutator, but I think this functionality is better suited for the model module, like the rest of the manipulator methods.

**Comment by AlexandreDecan** [comment]
The changes that concern a state or a transition that DO affect a statechart must be done using the ``Statechart`` API (see #30). The changes that concern a state or a transition that do NOT affect a statechart can be done directly on a ``State`` or ``Transition`` instance. 

For instance, the initial state of a ``CompoundState`` is not a read-only property and can be modified directly using its ``initial`` attribute. 

It's up to the developer to code a ``StatechartEditor`` that takes a ``Statechart`` instance and that manipulates the statechart, providing methods for each allowed change. The current ``Statechart`` API only provides the building bricks for such changes.

**Comment by AlexandreDecan** [comment]
I'll look how I can implement something like ``replace_state`` that could do the trick, batteries included.

**Comment by AlexandreDecan** [comment]
Too much work and logic for a single method.
