### ISSUE TITLE
Alternative to pykwalify

### ISSUE THREAD

**Issue by crdoconnor** [AlexandreDecan/sismic#52]
Hi,

I noticed on the kwalify issue tracker that you had the exact same problem as me (check the other issues).

FYI that nasty experience, among other issues with kwalify and YAML, made me write this alternative: https://github.com/crdoconnor/strictyaml

It's still something of a work in progress (I'll be adding kwalify support soon, for instance), but it's working. Any comments appreciated.

**Comment by AlexandreDecan** [comment]
This looks both interesting and promising. I'll give it a try asap.

**Comment by AlexandreDecan** [comment]
Fixed in 918c5f3be17168ae69057734d806f2ebe63fa65f 
The validation is now performed by ``schema`` against the Python structure (a direct translation of the schema previously defined in YAML).
