### ISSUE TITLE
Branch plantuml - export to plantuml

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/sismic#64]
Preliminary support to export statecharts to plantuml format, that can then be used at www.plantuml.com/plantuml/ to automatically render the statechart.

**Comment by tommens** [comment]
Remarque: La notation _old_.power est converti en underlined dans le rendu visuel. Cela n’est pas trop dérangeant, il faut juste le savoir...

Il faudra décider quelle visualisation on utilise dans le papier pour montrer les statecharts, mais il est important que ce soit une visualisation qui est supporté par sismic. S’il y en a deux (celui de plantuml et celui de Nikos), tant mieux, car cela permet de montrer que le support est “générique” et facile à ajouter.

Ton exemple du microwave oven controller est légèrement différent de celui dans le papier, donc on doit décider lequel on va prendre.

Cela ne me dérange pas de prendre ta version, mais il faut alors voir si cela implique qu’on va devoir faire des changements dans le papier à cause de cela.

Tom.

On 26 Feb 2018, at 13:09, Alexandre Decan <notifications@github.com> wrote:

Preliminary support to export statecharts to plantuml format, that can then be used at www.plantuml.com/plantuml/ to automatically render the statechart.

**Comment by AlexandreDecan** [comment]
Moved to devel
