### ISSUE TITLE
Implementing an Evaluator for a DSL

### ISSUE THREAD

**Issue by trulede** [AlexandreDecan/sismic#82]
Hi,

I'm looking into integrating a DSL into Sismic. The DSL is based on Python Lark and would manage some abstractions we have in our system which need to be resolved at run-time. One possible advantage we might gain from that is that DSL commands which run in Sismic will also run interactively - let's see .... its at least likely that a DSL commands would, indirectly, raise Events in the same Sismic model that called the DSL (via a Redis PubSub Channel).

From what I case see in the Sismic code I would need to create an Evaluator class and then pass an instance of that to the `Interpreter`. For any DSL specific parameters or initialisation it seems that I could use the initial_context parameter of the `Interpreter`.

Would it be better to base the class on PythonEvaluator and then override the `_evaluate_code()` and `_execute_code()` methods (and similar)? That might keep the behavior consistent between the DSL and PythonEvaluator, and allow for the management of `exposed_content` in the DSL (i.e. active, send, meta, time ...).

Does that seem right?

Thanks, Tim.

**Comment by trulede** [comment]
OK, I will base it from code/evaluator.py for the reasons stated. Would you have any problem if I refactored some of the code from python.py into evaluator.py and sent over a Pull Request? There are some improvements in python.py which could probably be moved back into the base Evaluator class, nothing special - compare execute_on_exit() as an example:

**evaluator.py**
```
def execute_on_exit(self, state: StateMixin) -> List[Event]:
        code = getattr(state, 'on_exit', None)
        if code:
            return self._execute_code(code)
        else:
            return []
```

**python.py**
```
def execute_on_exit(self, state: StateMixin) -> List[Event]:
        return self._execute_code(getattr(state, 'on_exit', None))
```

Thanks.

**Comment by AlexandreDecan** [comment]
Yes, feel free to do some refactoring on these files. Just keep in mind that `Evaluator` should be as simple as possible, for extension purposes. 

One possibility is to create a new `AdvancedEvaluator` (or something like that, e.g. `ContextBasedEvaluator`) that deals with all the goodies of the current PythonEvaluator, and delegates the evaluation of code to a concrete implementation (using `eval` and `exec`). That way, you'll be able to subclass the base class and to execute/evaluate code using your own DSL. 

I'm currently on a trip, so I can't work on this right now anyway ;)

**Comment by trulede** [comment]
Thanks. I have an idea to create some Mixin's for the various specialisations and then have the Python/DSL Evaluator focus on execute/eval. Lets see ...
