### ISSUE TITLE
parameterized events trigger a TypeError

### ISSUE THREAD

**Issue by Finfalter** [AlexandreDecan/sismic#84]
**Given** I have installed sismic 1.3.0 and I play with the elevator from the examples, [trying to execute the statemachine.](https://sismic.readthedocs.io/en/master/execution.html)

**When** I want to call `interpreter.queue('floorSelected', floor=1)`

**Then** I get TypeError: `queue() got an unexpected keyword argument 'floor'`
I get the same error when trying to execute any other statemachine.

**Comment by AlexandreDecan** [comment]
Hi, 

This version of the documentation corresponds to what is currently available on the master branch. The possibility to pass event parameters to `queue()` is something that will be added in Sismic 1.4.0 (not yet released on PyPI). For Sismic 1.3.0 and before, you should create an `Event` instance instead:

`interpreter.queue(Event('floorSelected', floor=1))`

Version 1.4.0 is expected to be released soon, but I cannot say when ;)

**Comment by Finfalter** [comment]
I switched to the master branch and it works fine for me.
Thanks for your help and your quick reply!

**Comment by AlexandreDecan** [comment]
You're welcome ;-)

Could I ask you in what context you intend to use Sismic? ;-)
