### ISSUE TITLE
JupyterLab Integration

### ISSUE THREAD

**Issue by trulede** [AlexandreDecan/sismic#85]
This is for discussion of an idea to make an integration with JuypterLab (https://jupyterlab.readthedocs.io/en/stable/).

We currently run Sismic in a Docker environment, and would like to extend this further. One idea we are considering is to build an interactive editing and execution interface using JuypterLab. The Docker environment would provide the Interpreter and Code evaluators within the JupyterLab framework. Meanwhile, the Statecharts would be "remoted" to the JupyterLab Browser based GUI so that Statecharts can be developed and debugged in real-time.

How exactly to do this is unclear. Transparent Proxy's, Statechart's which can merge in updated/changed YAML, bindings to Javascript representations via a Websockets.

**Comment by AlexandreDecan** [comment]
I think I'll need more information to understand what you're talking about ;-) 
I'm used to Jupyter lab, but I don't see exactly what you want to do/have?

**Comment by trulede** [comment]
A Web based IDE for the development of complex Sismic based Statecharts. Complex means many Statecharts which are bound together, distributed, and dynamically modified. We will want to visualise that too - but that's not your problem 😉 

We find the cloud based deployment method of Jupyter Lab interesting. At least it gives us a start point.

Question here is what might that mean for the core Sismic implementation? Currently I'm thinking about the Bind mechanism (I have another issue to open there) and how it might be possible to modify an "inflight" Statechart.

**Comment by trulede** [comment]
I would label it as a question.

**Comment by AlexandreDecan** [comment]
Ok, seems a little bit more concrete now :-)

**Comment by AlexandreDecan** [comment]
Is there anything I can do to support your work on this issue/feature request?

**Comment by AlexandreDecan** [comment]
Any news on this?
