### ISSUE TITLE
the code doesn't match the example for release 1.4.1

### ISSUE THREAD

**Issue by schaefer01** [AlexandreDecan/sismic#90]
the example on https://pythonhosted.org/sismic/advancedtopics/integrate_code.html
raises an exception.

I copied the example into example.py

app = StopwatchApplication(master=root)
  File "example.py", line 28, in __init__
    self.interpreter = Interpreter(statechart, initial_time=time.time())
TypeError: __init__() got an unexpected keyword argument 'initial_time'

**Comment by AlexandreDecan** [comment]
Hello,

Thanks for reporting this! The documentation on PythonHosted is not up-to-date at all (I don't know why, I've no control on this :-/). It refers to a very old release of Sismic. Please find an up-to-date version of the documentation on https://sismic.readthedocs.io/en/latest/.
