### ISSUE TITLE
Duplicate transitions after copying from another statechart 

### ISSUE THREAD

**Issue by jnwtr** [AlexandreDecan/sismic#91]
The Statechart class method copy_from_statechart(...) in the module model.statechart adds all transitions between copied states twice.

target statechart - state active to be replaced:
 
![target](https://user-images.githubusercontent.com/53007721/61939337-530e2500-af93-11e9-944a-b5165804b410.png)

source statechart - (root) state active to be copied:

![source](https://user-images.githubusercontent.com/53007721/61939252-23f7b380-af93-11e9-8d71-70d8fd875349.png)

result of copy_from_statechart(...):

![result](https://user-images.githubusercontent.com/53007721/61939291-37a31a00-af93-11e9-916d-f6e11151b53d.png)

I will send a pull request with a solution.

Kind regards,
Jan Wouter Versluis

**Comment by AlexandreDecan** [comment]
Thank you for having spotted this bug! I'll add some tests and then merge your PR asap.
