### ISSUE TITLE
Multiple instances of a statechart reg

### ISSUE THREAD

**Issue by chansdad** [AlexandreDecan/sismic#94]
I have question . In the documentation elevator or stop watch statecharts are explained. What is the upper limit for statecharts , ex , how many elevators can i create or how many stop watches can i create ? I really like the idea of YAML , and all the features , My use case is more like - creating multiple state machines , each maintaining its own state and able to interact with these state machines also would like to retain the current state between crashes and restarts. For instance , i want to create 1k elevators or 10k elevators and interact with each elevator . Any suggestions?

Thanks

**Comment by AlexandreDecan** [comment]
Hello,

There is no intrinsic limitation on the number of statecharts that Sismic can execute simultaneously. The only limitation will come from the performance of the machine. 

To execute many statecharts at once, the easiest way is to store them in a list:

```python
from sismic.io import import_from_yaml
from sismic.interpreter import Interpreter

statechart = import_from_yaml(filepath='elevator.yaml')
interpreters = [Interpreter(statechart) for i in range(10000)]

# Let's send the elevators to different floors
for i, interpreter in enumerate(interpreters):
    interpreter.queue('floorSelected', floor=i % 4)
    interpreter.execute()

# Let's check the current floor
print([i.context['current'] for i in interpreters])

```

.... this displays `[ 0, 1, 2, 3, 0, 1, 2, 3, .....]`.

**Comment by AlexandreDecan** [comment]
> also would like to retain the current state between crashes and restarts.

It depends on the complexity of your statecharts. Have a look at the following discussion: #89

**Comment by chansdad** [comment]
Thanks. This sure seems like something i can use. Do my idea is to have multiple elevators running ..and then be able to interact with each elevator from a different program .. while maintaining the state.. will give sismic a try .

**Comment by AlexandreDecan** [comment]
It is expected that you know these parameters (it should be part of the documented "API" of your statecharts), following Python's spirit. However, there is a way to retrieve the list of supported events for a given statechart with `statechart.events_for`. It reports about the event names that are used by the statechart, not about the parameters. 

Have a look at the second part of https://sismic.readthedocs.io/en/latest/execution.html#using-interpreter for more information.
