### ISSUE TITLE
Changing the name

### ISSUE THREAD

**Issue by gabewillen** [AlexandreDecan/sismic#98]
First I say this with the most respect. This is one of the best if not the best state machine library for python. The contract / behavior driven approach produces robust programs. It is however incredibly hard to find when searching on google. It doesn't even make the results with a simple "python statemachine" search. Search engines and keyboards want to auto-correct sismic to seismic. I really think more people would benefit from this library if it had a less cryptic name. I know your goal isn't recognition and you might not even care how many people use it. I just thought maybe you would consider a new name so that a larger portion of developers and beginners come across this library and benefit from it in the same way I have. Thanks for all the hard work in making this library!

**Comment by AlexandreDecan** [comment]
Thanks for this feedback! I really appreciate ;-) 

I'm not especially in favor of a name change for Sismic (originally it was even "pyss" for "Python Statechart Simulator" ^^). I think that if the library is not visible enough on Google & co, it's our responsibility to make it more popular and that results mentioning it are better placed on the results pages ;)

Do you have any suggestions for increasing the visibility of Sismic in general? 

We have submitted an article to SoftwareX (https://www.journals.elsevier.com/softwarex) which I hope will be published soon. I hope it will give some visibility within the scientific community. For industrials, I don't know how to make it more visible. Any suggestion is welcome! :-)

**Comment by gabewillen** [comment]
Well said maybe I can put together a really nice website for this project. Then possibly partner up with x-state the JavaScript scxml interpreter library that is hugely popular. You could link those interested in a similar project to Sismic using JavaScript to them and they could send those looking for a Python alternative to x-state to Sismic.

**Comment by AlexandreDecan** [comment]
Thanks for the offer! However, I don't think it's necessary to design a third site (considering that the github repository is the first one, and the documentation a second one). I think we should rather have more articles in blogs, newsletters, etc. to promote the library, and make the name "sismic" more visible on the major search engines.

**Comment by gabewillen** [comment]
Right that might be tough consider Microsoft has a machine learning framework called Seismic. In a way it might be better to keep it small while your still making design decisions. Less opinions to get in the way although ultimately yours and whoever else helped are all that matter.

**Comment by AlexandreDecan** [comment]
I close this since we are not going to change the name of the library, but we can still discuss about ways to promote the library :-)
